package graphscheduledrelease

func readyAuthorizationPayloadFrom(value ReadyAuthorization) readyAuthorizationPayload {
	return readyAuthorizationPayload{
		V: value.V, SchedulerProtocolVersion: value.SchedulerProtocolVersion,
		DispatchAuthorizationProtocolVersion: value.DispatchAuthorizationProtocolVersion,
		GraphRunID:                           value.GraphRunID, GraphID: value.GraphID,
		GroupRunID: value.GroupRunID, GroupID: value.GroupID,
		SourceSnapshotSHA256: value.SourceSnapshotSHA256,
		GraphManifestSHA256:  value.GraphManifestSHA256, CorePlanSHA256: value.CorePlanSHA256,
		ControlSnapshotSHA256:        value.ControlSnapshotSHA256,
		ReleaseControlSnapshotSHA256: value.ReleaseControlSnapshotSHA256,
		ProgressSnapshotSHA256:       value.ProgressSnapshotSHA256,
		ReconcileDecisionSHA256:      value.ReconcileDecisionSHA256,
		ScheduleID:                   value.ScheduleID, ScheduleSHA256: value.ScheduleSHA256,
		ScheduledContractID:            value.ScheduledContractID,
		ScheduledContractSHA256:        value.ScheduledContractSHA256,
		ScheduledProviderRequestID:     value.ScheduledProviderRequestID,
		ScheduledProviderRequestSHA256: value.ScheduledProviderRequestSHA256,
		LogicalRequestID:               value.LogicalRequestID, LogicalRequestSHA256: value.LogicalRequestSHA256,
		RequestBodySHA256: value.RequestBodySHA256, RequestBodyBytes: value.RequestBodyBytes,
		ExpectedLastEventSeq:    value.ExpectedLastEventSeq,
		ExpectedLastEventSHA256: value.ExpectedLastEventSHA256,
		ExecutionOrdinal:        value.ExecutionOrdinal, NodeID: value.NodeID, Attempt: value.Attempt,
		ProjectID: value.ProjectID, ProjectLaneSHA256: value.ProjectLaneSHA256,
		SameProjectPolicy: value.SameProjectPolicy, ProviderKind: value.ProviderKind,
		Endpoint: value.Endpoint, Model: value.Model, DestinationSHA256: value.DestinationSHA256,
		PricingSnapshotSHA256: value.PricingSnapshotSHA256, Budgets: value.Budgets,
		ReleaseRequirements:       value.ReleaseRequirements,
		MaximumFutureNodeReleases: value.MaximumFutureNodeReleases, Failure: value.Failure,
		LifecycleContractAdmissionAuthorized: value.LifecycleContractAdmissionAuthorized,
		ExecutionAuthorityReleaseAuthorized:  value.ExecutionAuthorityReleaseAuthorized,
		DispatchAuthorityReleaseAuthorized:   value.DispatchAuthorityReleaseAuthorized,
		ScheduledContractCandidatePresent:    value.ScheduledContractCandidatePresent,
		ProviderRequestPrepared:              value.ProviderRequestPrepared,
		LifecycleContractAdmitted:            value.LifecycleContractAdmitted,
		ExecutionAuthorityReleased:           value.ExecutionAuthorityReleased,
		DispatchAuthorityReleased:            value.DispatchAuthorityReleased,
		ProjectLaneClaimed:                   value.ProjectLaneClaimed, ProviderRequestSent: value.ProviderRequestSent,
		ProgressObserved: value.ProgressObserved, TerminalReceiptRecorded: value.TerminalReceiptRecorded,
		SuccessorAdvanceAuthorized: value.SuccessorAdvanceAuthorized,
	}
}
