package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func writeNativeClaudeStub(t *testing.T) string {
	t.Helper()
	return writeNativeClaudeCommand(t, "true")
}

func writeNativeClaudeCommand(t *testing.T, command string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "claude")
	writeNativeCommandAt(t, path, command, 0o700)
	return path
}

func writeNativeCommandAt(t *testing.T, path, command string, mode os.FileMode) {
	t.Helper()
	source, err := exec.LookPath(command)
	if err != nil {
		t.Skipf("%s is unavailable: %v", command, err)
	}
	source, err = filepath.EvalSymlinks(source)
	if err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(source)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, data, mode); err != nil {
		t.Fatal(err)
	}
}

func buildNativeFakeClaude(t *testing.T, path, behavior string) {
	t.Helper()
	verdict := "APPROVE"
	for _, candidate := range []string{"REQUEST_CHANGES", "MAYBE"} {
		if strings.Contains(behavior, "VERDICT: "+candidate) {
			verdict = candidate
			break
		}
	}
	source := strings.ReplaceAll(nativeFakeClaudeSource, "__VERDICT__", strconv.Quote(verdict))
	sourcePath := path + ".go"
	if err := os.WriteFile(sourcePath, []byte(source), 0o600); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "build", "-trimpath", "-o", path, sourcePath)
	cache := filepath.Join(os.TempDir(), "forgeos-native-fake-gocache")
	cmd.Env = append(os.Environ(), "GOCACHE="+cache)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build native fake Claude: %v\n%s", err, output)
	}
}

const nativeFakeClaudeSource = `package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const verdict = __VERDICT__

func main() {
	data, _ := io.ReadAll(os.Stdin)
	prompt := string(data)
	phase := phaseOf(prompt)
	writePhaseArtifacts(phase, prompt)
	result := "VERDICT: " + verdict
	switch phase {
	case "requirement-discovery":
		result = "CONFIDENCE: 100"
	case "scan":
		result = scanReport(prompt)
	case "planner", "roadmap-update":
		result = "TASK_LIST:\n- [ ] T001: deterministic task — acceptance: pass — files: docs/fake.md — depends_on: none — model: sonnet — roadmap: v2"
	case "qa":
		result = "QA_VERDICT: ACCEPTED"
		if verdict != "APPROVE" {
			result = "QA_VERDICT: " + verdict
		}
	}
	envelope := map[string]any{
		"type": "result", "subtype": "success", "is_error": false,
		"result": result, "total_cost_usd": 0,
	}
	_ = json.NewEncoder(os.Stdout).Encode(envelope)
}

func scanReport(prompt string) string {
	depth := "standard"
	for _, candidate := range []string{"advisory", "opportunistic", "standard", "thorough"} {
		if strings.Contains(prompt, "Effective mode×lifecycle scan depth: "+candidate) {
			depth = candidate
			break
		}
	}
	names := []string{"code"}
	if depth == "thorough" {
		names = []string{"code", "dependencies", "security", "performance", "architecture_drift", "test_coverage"}
	}
	dimensions := make([]map[string]any, 0, len(names))
	for _, name := range names {
		dimensions = append(dimensions, map[string]any{
			"name": name, "status": "clear",
			"evidence": []map[string]any{{
				"path": ".agent/ROADMAP.md", "line": 1,
				"detail": "deterministic fake inspected repository roadmap for " + name,
			}},
		})
	}
	report := map[string]any{
		"version": "evolve_scan_v1", "depth": depth,
		"dimensions": dimensions, "opportunities": []any{},
	}
	data, _ := json.Marshal(report)
	return "EVOLVE_SCAN_V1: " + string(data)
}

func phaseOf(prompt string) string {
	_, rest, ok := strings.Cut(prompt, "phase=")
	if !ok {
		return ""
	}
	phase, _, _ := strings.Cut(rest, ",")
	return strings.TrimSpace(phase)
}

func appendArtifact(path, phase string) {
	_ = os.MkdirAll(filepath.Dir(path), 0o755)
	file, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return
	}
	_, _ = fmt.Fprintf(file, "generated by deterministic fake agent: %s\n", phase)
	_ = file.Close()
}

func writeMany(phase string, paths ...string) {
	for _, path := range paths {
		appendArtifact(path, phase)
	}
}

func writePhaseArtifacts(phase, prompt string) {
	switch phase {
	case "requirement-discovery":
		writeMany(phase, "docs/discovery/requirement-draft.md")
	case "market-research":
		writeMany(phase, "docs/discovery/capability-matrix.md", "docs/discovery/citations.md")
	case "product-design":
		writeMany(phase, "docs/discovery/prd.md")
	case "solution-architect":
		writeDesignADR(phase, prompt)
	case "proposal-generator":
		writeMany(phase, "docs/design/proposal.md")
	case "security-review":
		writeMany(phase, "docs/review/security-review.md", "docs/review/threat-model.md")
	case "distributed-review":
		writeMany(phase, "docs/review/distributed-review.md")
	case "performance-reliability-review":
		writeMany(phase, "docs/review/performance-budget.md", "docs/review/production-readiness.md")
	case "executive-review":
		writeMany(phase, "docs/design/review-summary.md")
	case "planner":
		writeMany(phase, ".agent/CURRENT_SPRINT.md")
	case "gap-analysis":
		writeMany(phase, "docs/design/gap-report.md")
	case "roadmap-update":
		_ = os.MkdirAll(".agent", 0o755)
		_ = os.WriteFile(".agent/ROADMAP.md", []byte("# Deterministic roadmap\n- [x] fake gap closed\n"), 0o600)
	case "evaluate":
		writeMany(phase, "docs/review/eval-scorecard.md")
	case "release-planning":
		writeMany(phase, "docs/release/release-manifest.yml", "docs/release/deployment-plan.md",
			"docs/release/deployment-runbook.md", "docs/release/go-no-go-checklist.md")
	case "release-plan-validation":
		writeMany(phase, "docs/release/deployment-validation.md")
		appendVerdict("docs/release/deployment-validation.md")
	case "rollback-planning":
		writeMany(phase, "docs/release/rollback-plan.md", "docs/release/rollback-runbook.md",
			"docs/release/rollback-checklist.md")
	case "rollback-plan-validation":
		writeMany(phase, "docs/release/rollback-validation.md")
		appendVerdict("docs/release/rollback-validation.md")
	}
}

func writeDesignADR(phase, prompt string) {
	match := regexp.MustCompile("next available: ADR-([0-9]+)-\\*\\.md").FindStringSubmatch(prompt)
	if len(match) == 2 {
		writeProposedADRV2("ADR-"+match[1], "Deterministic Design")
	}
}

func writeProposedADRV2(adrID, title string) {
	name := adrID + "-deterministic-design.md"
	body := fmt.Sprintf("# %s: %s\n\n## Context\nThe deterministic fake needs an architecture decision.\n\n## Decision\nEmit exact proposed-only ADR v2 bytes.\n\n## Consequences\nWorkflow tests exercise strict ADR validation.\n\n## Validation\nRun the shipped workflow end-to-end test.\n\n## Limitations\nThis fixture carries no approval or authority.\n", adrID, title)
	metadata := fakeADRMetadata(name, adrID, title)
	metadata["body_sha256"] = fakeADRDigest("forgeos.architecture-decision-record-body.v2\x00", []byte(body))
	blank, _ := json.Marshal(metadata)
	metadata["self_sha256"] = fakeADRDigest("forgeos.architecture-decision-record.v2\x00",
		append(append(blank, 0), []byte(body)...))
	frontmatter, _ := json.Marshal(metadata)
	path := filepath.Join("docs", "adr", name)
	_ = os.MkdirAll(filepath.Dir(path), 0o755)
	_ = os.WriteFile(path, []byte("---\n"+string(frontmatter)+"\n---\n\n"+body), 0o600)
}

func fakeADRMetadata(name, adrID, title string) map[string]any {
	return map[string]any{
		"acceptance_id": nil, "accepted_at_unix_ms": nil, "adr_id": adrID,
		"affected_node_ids": []string{},
		"alternatives": []map[string]any{
			{"alternative_id": "candidate-v2", "description": "Use exact v2 bytes.", "disposition": "candidate", "rationale": "It is deterministic."},
			{"alternative_id": "rejected-yaml", "description": "Use general YAML.", "disposition": "rejected", "rationale": "It is ambiguous."}},
		"api_version": "forgeos.architecture-decision-record/v2", "approver_refs": []string{"role:reviewer"},
		"assumption_claim_ids": []string{}, "body_sha256": "", "canonicalization": "forgeos.canonical-json/v1",
		"compatibility": "Legacy ADRs remain unchanged.", "consequences": []string{"New ADRs have deterministic bytes."},
		"context_claim_ids": []string{}, "decision": "Emit an exact proposed-only ADR v2 document.",
		"decision_driver_claim_ids": []string{}, "document_name": name, "evidence_record_ids": []string{},
		"expires_at_unix_ms": nil, "implementation_refs": []string{}, "kind": "ArchitectureDecisionRecord",
		"owner_refs": []string{"role:architect"}, "proposed_at_unix_ms": int64(1),
		"revisit_triggers": []map[string]any{{"condition": "The lifecycle contract changes.", "evidence_required": []string{"An adopted replacement contract."}, "trigger_id": "lifecycle-change"}},
		"risks": []any{}, "rollback": "Stop emitting the test fixture.", "rollout": "Use it only in tests.",
		"scope_refs": []string{"repo:architecture"}, "self_sha256": "", "status": "proposed",
		"superseded_by": []string{}, "supersedes": []string{}, "title": title,
		"validation_plan": []map[string]any{{"description": "Run the shipped workflow.", "due_trigger": "During the test.", "evidence_required": []string{"A passing end-to-end test."}, "owner_ref": "role:architect", "success_criteria": "The ADR is captured.", "validation_id": "workflow-test"}},
	}
}

func fakeADRDigest(prefix string, data []byte) string {
	digest := sha256.Sum256(append([]byte(prefix), data...))
	return fmt.Sprintf("%x", digest[:])
}

func appendVerdict(path string) {
	file, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return
	}
	_, _ = fmt.Fprintln(file, "VERDICT: "+verdict)
	_ = file.Close()
}
`
