use super::super::super::{
    CREATE_V1_SCHEMA_SQL, MIGRATE_V1_TO_V2_SQL, MIGRATE_V2_TO_V3_SQL, MIGRATE_V3_TO_V4_SQL,
    MIGRATE_V4_TO_V5_SQL, MIGRATE_V5_TO_V6_SQL, MIGRATE_V6_TO_V7_SQL, MIGRATE_V7_TO_V8_SQL,
    MIGRATE_V8_TO_V9_SQL, MIGRATE_V9_TO_V10_SQL, MIGRATE_V10_TO_V11_SQL, MIGRATE_V11_TO_V12_SQL,
    MIGRATE_V12_TO_V13_SQL, MIGRATE_V13_TO_V14_SQL, MIGRATE_V14_TO_V15_SQL, MIGRATE_V15_TO_V16_SQL,
    MIGRATE_V16_TO_V17_SQL, MIGRATE_V17_TO_V18_SQL, MIGRATE_V18_TO_V19_SQL, MIGRATE_V19_TO_V20_SQL,
    MIGRATE_V20_TO_V21_SQL, MIGRATE_V21_TO_V22_SQL, MIGRATE_V22_TO_V23_SQL, MIGRATE_V23_TO_V24_SQL,
    MIGRATE_V24_TO_V25_SQL, MIGRATE_V25_TO_V26_SQL, MIGRATE_V26_TO_V27_SQL, MIGRATE_V27_TO_V28_SQL,
    MIGRATE_V28_TO_V29_SQL, MIGRATE_V29_TO_V30_SQL, MIGRATE_V30_TO_V31_SQL, MIGRATE_V31_TO_V32_SQL,
    MIGRATE_V32_TO_V33_SQL, MIGRATE_V33_TO_V34_SQL,
};

pub(super) const OWNED_TABLES: &[&str] = &[
    "projects",
    "groups",
    "conversations",
    "group_projects",
    "prompts",
    "runs",
    "run_events",
    "run_assistant_prompts",
    "group_runs",
    "group_executions",
    "group_execution_events",
    "group_model_analyses",
    "group_model_analysis_events",
    "group_model_analysis_results",
    "group_analysis_panels",
    "group_analysis_panel_analyses",
    "group_panel_syntheses",
    "group_panel_synthesis_events",
    "group_panel_synthesis_results",
    "group_agent_graphs",
    "group_agent_graph_runs",
    "group_agent_graph_run_events",
    "group_agent_graph_node_execution_contracts",
    "group_agent_graph_node_dispatch_requests",
    "group_agent_graph_node_dispatch_claims",
    "group_agent_project_lane_ownerships",
    "group_agent_graph_node_terminal_artifacts",
    "group_agent_graph_node_terminal_receipts",
    "group_agent_graph_execution_schedules",
    "group_agent_graph_scheduled_node_contract_candidates",
    "group_agent_graph_scheduled_node_provider_requests",
    "group_agent_graph_scheduled_node_dispatch_lifecycles",
    "group_agent_graph_scheduled_node_successor_candidates",
    "governance_record_append_batches",
    "governance_records",
    "governance_structural_heads",
    "governance_semantic_heads",
    "governance_claim_semantic_views",
    "governance_claim_validation_jobs",
    "run_lineages",
    "group_agent_scheduled_graph_controllers",
    "group_agent_scheduled_graph_controller_events",
    "conversation_change_baselines",
    "conversation_changes",
    "conversation_change_state",
    "conversation_change_heads",
    "conversation_owners",
    "conversation_owner_change_heads",
    "conversation_owner_change_rows",
    "project_execution_consent_grants",
    "project_execution_consent_events",
    "pending_run_intents",
    "pending_run_intent_events",
];

pub(super) const SCHEMA_BATCHES: &[&str] = &[
    CREATE_V1_SCHEMA_SQL,
    MIGRATE_V1_TO_V2_SQL,
    MIGRATE_V2_TO_V3_SQL,
    MIGRATE_V3_TO_V4_SQL,
    MIGRATE_V4_TO_V5_SQL,
    MIGRATE_V5_TO_V6_SQL,
    MIGRATE_V6_TO_V7_SQL,
    MIGRATE_V7_TO_V8_SQL,
    MIGRATE_V8_TO_V9_SQL,
    MIGRATE_V9_TO_V10_SQL,
    MIGRATE_V10_TO_V11_SQL,
    MIGRATE_V11_TO_V12_SQL,
    MIGRATE_V12_TO_V13_SQL,
    MIGRATE_V13_TO_V14_SQL,
    MIGRATE_V14_TO_V15_SQL,
    MIGRATE_V15_TO_V16_SQL,
    MIGRATE_V16_TO_V17_SQL,
    MIGRATE_V17_TO_V18_SQL,
    MIGRATE_V18_TO_V19_SQL,
    MIGRATE_V19_TO_V20_SQL,
    MIGRATE_V20_TO_V21_SQL,
    MIGRATE_V21_TO_V22_SQL,
    MIGRATE_V22_TO_V23_SQL,
    MIGRATE_V23_TO_V24_SQL,
    MIGRATE_V24_TO_V25_SQL,
    MIGRATE_V25_TO_V26_SQL,
    MIGRATE_V26_TO_V27_SQL,
    MIGRATE_V27_TO_V28_SQL,
    MIGRATE_V28_TO_V29_SQL,
    MIGRATE_V29_TO_V30_SQL,
    MIGRATE_V30_TO_V31_SQL,
    MIGRATE_V31_TO_V32_SQL,
    MIGRATE_V32_TO_V33_SQL,
    MIGRATE_V33_TO_V34_SQL,
];

pub(super) const VERSION_TABLE_COUNTS: [usize; 35] = [
    0, 5, 8, 9, 11, 14, 16, 19, 20, 22, 23, 24, 28, 29, 30, 31, 32, 33, 33, 33, 33, 33, 33, 33, 33,
    36, 36, 39, 40, 42, 46, 47, 49, 51, 53,
];

pub(super) const VERSION_EXPLICIT_INDEX_COUNTS: [usize; 35] = [
    0, 2, 3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 24, 25, 27, 29, 31, 32, 32, 32, 32, 32, 32, 32, 32,
    35, 35, 38, 39, 40, 42, 43, 45, 46, 47,
];
